[2024-09-03T04:49:44.380+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:49:44.393+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:49:44.406+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:49:44.404+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:49:44.712+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:49:44.686+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:49:44.715+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:49:44.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.552 seconds
[2024-09-03T04:50:15.050+0000] {processor.py:186} INFO - Started process (PID=186) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:50:15.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:50:15.053+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:50:15.053+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:50:15.180+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:50:15.176+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:50:15.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:50:15.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.224 seconds
[2024-09-03T04:50:45.577+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:50:45.578+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:50:45.581+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:50:45.580+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:50:45.689+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:50:45.685+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:50:45.692+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:50:45.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.181 seconds
[2024-09-03T04:51:16.146+0000] {processor.py:186} INFO - Started process (PID=218) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:51:16.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:51:16.157+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:51:16.156+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:51:16.265+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:51:16.261+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:51:16.267+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:51:16.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.192 seconds
[2024-09-03T04:51:47.036+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:51:47.037+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:51:47.040+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:51:47.039+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:51:47.143+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:51:47.137+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:51:47.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:51:49.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 2.582 seconds
[2024-09-03T04:54:39.462+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:54:39.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:54:39.467+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:54:39.466+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:54:39.598+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:54:39.593+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:54:39.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:54:39.672+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.219 seconds
[2024-09-03T04:55:09.766+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:55:09.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:55:09.770+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:55:09.770+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:55:09.882+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:55:09.878+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:55:09.884+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:55:09.938+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.178 seconds
[2024-09-03T04:55:40.137+0000] {processor.py:186} INFO - Started process (PID=216) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:55:40.138+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:55:40.141+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:55:40.141+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:55:40.271+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:55:40.266+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:55:40.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:55:40.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.213 seconds
[2024-09-03T04:56:10.612+0000] {processor.py:186} INFO - Started process (PID=230) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:56:10.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:56:10.616+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:56:10.615+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:56:10.737+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:56:10.734+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:56:10.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:56:10.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.204 seconds
[2024-09-03T04:56:41.119+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:56:41.120+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:56:41.123+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:56:41.122+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:56:41.263+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:56:41.257+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:56:41.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:56:41.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.345 seconds
[2024-09-03T04:57:11.725+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:57:11.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/xray_test_dag.py for tasks to queue
[2024-09-03T04:57:11.729+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:57:11.728+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:57:11.990+0000] {logging_mixin.py:190} INFO - [2024-09-03T04:57:11.986+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/xray_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/xray_test_dag.py", line 12, in <module>
    post_string = os.environ['post_string']
                  ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2024-09-03T04:57:11.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/xray_test_dag.py
[2024-09-03T04:57:12.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/xray_test_dag.py took 0.341 seconds
